HOST: http://v2.api.cape.io/

--- CAPE API v2 ---
---
Welcome to the Create Anywhere Publish Everywhere API documentation. [CAPE.io](http://cape.io)
---

--
Internal - Raw Data Resources
The following is a section of resources related to getting at core data.
--
List the value(s) of a specific key.

+ Parameters
    + app_id (string, required) ... Id of a post.
        + Example: `share`, `supersimple`, `github_static`

GET /_cape_redis/{app_id}/{entity_type}/{data_type}/{entity_id}.json{?string,value,expire_in_sec,all_values}
< 200
< Content-Type: application/json
{ "items": [
{ "url": "/shopping-cart/1", "product":"2ZY48XPZ", "quantity": 1, "name": "New socks", "price": 1.25 }
] }


Save new products in your shopping cart
POST /_cape_user/
> Content-Type: application/json
{ "product":"1AB23ORM", "quantity": 2 }
< 201
< Content-Type: application/json
{ "status": "created", "url": "/shopping-cart/2" }

-- Payment Resources --
This resource allows you to submit payment information to process your *shopping cart* items
POST /payment
{ "cc": "12345678900", "cvc": "123", "expiry": "0112" }
< 200
{ "receipt": "/payment/receipt/1" }